# GitHub Actions workflow for testing and continuous integration.
#
# This file performs testing using tox and tox.ini to define and configure the test environments.

name: CI

on:
  push:
    branches:
    - main  # GitHub now defaults to 'main' as the name of the primary branch. Change this as needed.
  #  tags: # run CI if specific tags are pushed
  pull_request:
  #  branches: # only build on PRs against 'main' if you need to further limit when CI is run.
  #  - main

jobs:
  # Github Actions supports ubuntu, windows, and macos virtual environments:
  # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
  ci_tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Code style checks
            os: ubuntu-latest
            python: 3.x
            toxenv: check-style

          - name: Security audit
            os: ubuntu-latest
            python: 3.x
            toxenv: check-security

          - name: Python 3.9 with oldest supported dependencies
            os: ubuntu-latest
            python: 3.9
            toxenv: test-oldestdeps

          - name: Python 3.11 with coverage checking
            os: ubuntu-latest
            python: 3.11
            toxenv: test-cov

          - name: OS X - Python 3.10
            os: macos-latest
            python: 3.10
            toxenv: test

          - name: Windows - Python 3.10
            os: windows-latest
            python: 3.10
            toxenv: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up python ${{ matrix.python }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Test with tox
      run: |
        tox -e ${{ matrix.toxenv }}
